# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '88c65941-e6fa-4fe3-98b6-48b16bc27c9a'
  imageRepository: 'pythonazuredevopscontainerized'
  containerRegistry: 'ansalemocontainerregistry.azurecr.io'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  webApp: 'pythonazuredevopscontainerized'
  azureSubscription: '4388fa06-bf66-4497-82c2-991ba75ecb97'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: Deploy
  displayName: Azure App Service Deploy
  jobs: 
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureRMWebAppDeployment@4
      displayName: Azure App Service Deploy
      inputs:
        appType: webAppContainer
        ConnectedServiceName: $(azureSubscription)   
        WebAppName: $(webApp)
        DockerNamespace: $(containerRegistry) 
        DockerRepository: $(imageRepository) 
        DockerImageTag: $(tag)

